### ISSUE TITLE
apt (tensorflow-arm-neoverse): E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)

### ISSUE THREAD

**Issue by Altair-Bueno** [ARM-software/Tool-Solutions#169] opened 2023-03-07 09:28 UTC
I'm unable to install software using `apt` with the image `armswdev/tensorflow-arm-neoverse`. I tried multiple solutions I found online to remove the lock, but there is no root access on the image. How can I install additional packages?

- [Using `tensorflow/tensorflow` as the base image](https://github.com/ertis-research/fission-environments/blob/master/tensorflow-arm/Dockerfile) creates the image successfully with no workarounds
- [Link log where apt is unable to get the lock](https://github.com/ertis-research/fission-environments/actions/runs/4347059602/jobs/7593902775#step:6:408)
- [Link to all my GitHub Actions runs with different solutions](https://github.com/ertis-research/fission-environments/actions)

**Comment by nSircombe** [comment] 2023-03-07 09:34
Hi @Altair-Bueno,

You should be able to use `sudo apt-get install <package>` within the image - does this not work for you?
What package(s) are you trying to add to the image?

...one alternative solution would be to update the package list (here: https://github.com/ARM-software/Tool-Solutions/blob/be380cbe1a9cfe30b70f7a7ae8b2ad3b301a9144/docker/tensorflow-aarch64/Dockerfile#L36) and build your own Docker image (as per https://github.com/ARM-software/Tool-Solutions/blob/main/docker/tensorflow-aarch64/README.md#build-tensorflow-2x-for-aarch64-using-docker - `./build.sh --onednn acl_threadpool`

**Comment by nSircombe** [comment] 2023-03-07 11:10
> It doesn't.

Hummm... that's strange. It works interactively. I'm not sure what the issue is for your pipeline.

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/32057673/223405157-82bcdb61-f91f-4e37-b974-55253fae87b7.png">

_(note: python3-dev should already be in there)_

**Comment by Altair-Bueno** [comment] 2023-03-07 12:10
> Hummm... that's strange. It works interactively. I'm not sure what the issue is for your pipeline.

For context, my build action is based on the README example GitHub provides. I checked the versions and everything looks up to date. The action is based on Docker's Buildx

- [Link to README example](https://github.com/marketplace/actions/build-and-push-docker-images)
- [Link to my build action YAML](https://github.com/ertis-research/fission-environments/blob/master/.github/workflows/build.yml)

I recreated this issue with a more minimalistic setup [here](https://github.com/Altair-Bueno/bug-apt-tensorflow-arm). Latest workflow run still fails ([logs](https://github.com/Altair-Bueno/bug-apt-tensorflow-arm/actions/runs/4353899755/jobs/7608526136#step:6:346)).

**Comment by Altair-Bueno** [comment] 2023-03-07 12:27
Update: I ran buildx (build.sh) locally on my machine and the image build successfully. Looks like an buildx issue 

```yml
os: macOS Ventura 13.2.1 (22D68)
cpu: 1,4 GHz Quad-Core Intel Core i5 (x86_64)
buildx: github.com/docker/buildx v0.10.2 00ed17df6d20f3ca4553d45789264cdb78506e5f
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.19.5
 Git commit:        a5ee5b1dfc
 Built:             Thu Feb  9 19:15:59 2023
 OS/Arch:           darwin/amd64
 Context:           colima

Server:
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974ae9e6c219862907efdd76ec2e77ec930b
  Built:            Wed Oct 19 02:58:31 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Comment by Altair-Bueno** [comment] 2023-03-07 12:54
Update 2: Installing QEMU on the runner solves this issue

https://github.com/Altair-Bueno/bug-apt-tensorflow-arm/blob/692ca1069953f4bab1bdd05f28a45d8c8f98364d/.github/workflows/workflow.yml#L23

My original image finally compiled successfully too. This wasn't a great error message from Buildx

**Comment by nSircombe** [comment] 2023-03-07 15:22
ok, great - so you're unblocked then? Are we ok to close this issue.

...I should probably have noted in my original answer that my builds are not using QEMU - our build & test is on AArch64 hardware - Neoverse N1 or V1 usually.

If you don't mind me asking, just out of curiosity, what are you using the Tool Solutions images for

**Comment by Altair-Bueno** [comment] 2023-03-07 15:56
> ok, great - so you're unblocked then? Are we ok to close this issue.

Yep, pipeline looks great. That Buildx error was something I've never seen before. Thanks for your time!

> If you don't mind me asking, just out of curiosity, what are you using the Tool Solutions images for?

We are extending our [DDNN framework](https://github.com/ertis-research/DDNN) to work as serverless functions on amd64 and arm64 platforms, leveraging open source serverless frameworks. These frameworks provide base docker images but none of them offer up-to-date tensorflow images. And none of them offer arm64 variants.

**Comment by nSircombe** [comment] 2023-03-08 08:19
Hi @Altair-Bueno,

Thanks for the info. I wasn't aware of your DDNN framework.

I should point out though that these Docker images are really intended for the purposes of evaluation / experimentation, rather than any production deployment (as per the [readme](https://github.com/ARM-software/Tool-Solutions/blob/main/docker/tensorflow-aarch64/README.md)).

AArch64 support is available now in the release versions of both TensorFlow and PyTorch. 
Som in the case of TensorFlow you can just `pip install` it now and  AArch64-specific optimisations can be enabled by setting the env. var. `TF_ENABLE_ONEDNN_OPTS=1`.

**Closed by nSircombe** 2023-03-08 08:19 UTC
Labels: help wanted

**Comment by Altair-Bueno** [comment] 2023-03-08 09:09
> AArch64 support is available now in the release versions of both TensorFlow and PyTorch.

Oh I didn't know that. Do you know if there are any plans to create official `tensorflow/tensorflow` images for arm64? That would reduce our complexity. For now we are just testing if things work as we expect, it's nothing production ready

**Comment by nSircombe** [comment] 2023-03-08 21:58
> Do you know if there are any plans to create official tensorflow/tensorflow images for arm64? 
Not that I'm aware of, but it couldn't hurt to raise an issue on the TF GitHub.
