### ISSUE TITLE
UnitTests failed 

### ISSUE THREAD

**Issue by alexhegit** [ARM-software/Tool-Solutions#4] opened 2019-03-28 07:24 UTC
I do native build the armnn with the script but the UnitTests failed. The platform is Ultar96(armv8) w/ Ubuntu18.04.

xilinx@pynq:~/armnn-devenv/armnn/build$ ./UnitTests
Warning gator_func(/home/xilinx/armnn-devenv/gator/annotate/streamline_annotate.c:496): Not connected to gatord, the application will run normally but Streamline will not collect annotations. To collect annotations, please verify you are running gatord 5.24 or later and that SELinux is disabled.
Running 758 test cases...
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "NeonLayerSupport/IsLayerSupportedFloat16Neon": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(471): last checkpoint
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "NeonLayerSupport/IsLayerSupportedFloat32Neon": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(471): last checkpoint
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "NeonLayerSupport/IsLayerSupportedUint8Neon": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(471): last checkpoint
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "RefLayerSupported/IsLayerSupportedLayerTypeMatches": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(544): last checkpoint
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "RefLayerSupported/IsLayerSupportedFloat16Reference": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(471): last checkpoint
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "RefLayerSupported/IsLayerSupportedFloat32Reference": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(443): last checkpoint
UnitTests: /home/xilinx/armnn-devenv/armnn/src/armnn/InternalTypes.cpp:49: const char* armnn::GetLayerTypeAsCString(armnn::LayerType): Assertion `(false)&&("Unknown layer type")' failed.
unknown location(0): fatal error: in "RefLayerSupported/IsLayerSupportedUint8Reference": signal: SIGABRT (application abort requested)
/home/xilinx/armnn-devenv/armnn/src/backends/backendsCommon/test/IsLayerSupportedTestImpl.hpp(471): last checkpoint

*** 7 failures are detected in the test module "UnitTests"

**Comment by jasonrandrews** [comment] 2019-04-01 13:37
Hi, thanks for reporting the errors. 

There are similar errors on other boards so it's nothing specific to the Ultra96 board. The errors are caused by the Streamline instrumentation for performance analysis and will be fixed in the future. 

If you want to build and run without errors (and without the Streamline annotation) you can use the official 18.11 releases of Compute Library and Arm NN. 

Edit the build-armnn.sh script to get them:

For Compute library:
git clone -b v18.11 --single-branch https://github.com/ARM-software/ComputeLibrary.git

For Arm NN
git clone -b v18.11  --single-branch https://github.com/ARM-software/armnn.git

With these you should be able to build as before and all UnitTests will pass. 

We are also planning to update the examples to the 19.02 release of CL and NN soon.

**Closed** 2021-03-26 20:24 UTC
