### ISSUE TITLE
Failing to get oneDNN patch when building Tool-Solutions PyTorch docker image

### ISSUE THREAD

**Issue by milpuz01** [ARM-software/Tool-Solutions#260] opened 2024-12-06 22:58 UTC
When getting sources here: https://github.com/ARM-software/Tool-Solutions/blob/7840604ed2531adb256275d7f82ab293f3913c09/docker/pytorch-aarch64/get-source.sh#L95-L96 for oneDNN PR: https://github.com/oneapi-src/oneDNN/pull/2198 it fails to find the commits listed there because that PR was updated couple of days ago so commit hashes need to be updated to:

* 59bedbdc88e9af9100b5f655020d58764610055c for matmul static quantization, and
* d728790380d9d983dcdf14e1477008126fcfc434 for convolution static quantization

**Comment by nSircombe** [comment] 2024-12-07 09:13
It's possible to download a .patch made from all commits in a PR and apply that. Wouldn't it be preferable to do that rather than curl-ing individual commits from inside a pr? Or is a commit-by-commit level of granularity needed somewhere?

**Comment by renato-arantes** [comment] 2024-12-07 11:15
I already have a fix for this in place. Need IP review.

**Comment by renato-arantes** [comment] 2024-12-07 18:09
This [PR](https://github.com/ARM-software/Tool-Solutions/pull/261) fixes the issue.

**Closed** 2024-12-08 11:33 UTC

**Comment by jondea** [comment] 2024-12-09 09:07
We fix the hash of the base sources, so I think it makes sense to fix the specific _commits_ we get from each PR. Otherwise, the head of the PR could move on, and the patch may no longer apply. I generally went with the principle of reproducibility and traceability over all else.

I'm surprised this failed actually, I was under the impression that even if you force pushed to a PR, the previous commits were still stored and could be referenced by that URL. We tried to test this, but I must have done something slightly different.

So, the commits still "exists" in the oneDNN repo,
https://github.com/oneapi-src/oneDNN/commit/6a77e84feb442964c91a0101d58fe1473566b185
https://github.com/oneapi-src/oneDNN/commit/efad4f6582c13823d81c78130ab80db57b1381eb

but is no longer accessible via the specific PR endpoint
https://github.com/oneapi-src/oneDNN/pull/2198/commits/6a77e84feb442964c91a0101d58fe1473566b185
https://github.com/oneapi-src/oneDNN/pull/2198/commits/efad4f6582c13823d81c78130ab80db57b1381eb

The pragmatic thing may be to use the generic endpoint rather than the PR specific one. The reason I went with the PR one was to "check" that the PR was indeed the correct one, and to force the developer to associate a commit with the PR. I think this may be a small price to pay.

**Comment by nSircombe** [comment] 2024-12-09 09:11
> Edit: ohhhh, that's weird, GitHub "fixes" the link in this GitHub comment when I use the PR endpoint

You mean it tried to put the non-PR-specific path in?

>The reason I went with the PR one was to "check" that the PR was indeed the correct one, and to force the developer to associate a commit with the PR. I think this may be a small price to pay.

I think going with non-PR-specific paths is probably best on balance.

**Comment by jondea** [comment] 2024-12-09 09:13
> You mean it tried to put the non-PR-specific path in?

Yes, if you post those links without code blocks, they resolve to the same place when you click submit
